# Generated by Django 4.0.5 on 2022-07-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aplicacion1', '0018_relationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.CharField(max_length=255)),
                ('nombrePost', models.CharField(max_length=255)),
                ('CuerpoPost', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion2.grupo')),
                ('usuario_en_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion2.usuario2')),
            ],
        ),
    ]
