# Generated by Django 4.0.5 on 2022-07-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0019_alter_usuario_id'),
        ('Aplicacion2', '0003_grupo_usuario_remove_usuario_grupo_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario2',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.perfil'),
        ),
    ]
