# Generated by Django 4.0.5 on 2022-07-19 09:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion1', '0019_alter_usuario_id'),
        ('Aplicacion2', '0004_alter_usuario2_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario2',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.usuario'),
        ),
        migrations.CreateModel(
            name='GPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePost', models.CharField(max_length=50)),
                ('CuerpoPost', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Subir imagen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
