# Generated by Django 4.0.5 on 2022-07-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0006_gpost_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpost',
            name='related',
        ),
        migrations.AddField(
            model_name='grupo',
            name='relatedGrupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion2.gpost'),
        ),
    ]
