# Generated by Django 4.0.5 on 2022-07-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0007_remove_gpost_related_grupo_relatedgrupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='relatedGrupo',
        ),
        migrations.AddField(
            model_name='gpost',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion2.grupo'),
        ),
        migrations.AlterField(
            model_name='gpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
