# Generated by Django 4.0.5 on 2022-07-25 18:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0008_remove_grupo_relatedgrupo_gpost_related_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario2',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='gpost',
            name='related',
        ),
        migrations.AlterField(
            model_name='gpost',
            name='CuerpoPost',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Que piensas?'),
        ),
        migrations.AlterField(
            model_name='gpost',
            name='nombrePost',
            field=models.CharField(max_length=50, verbose_name='Titulo de post'),
        ),
        migrations.DeleteModel(
            name='Grupo_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario2',
        ),
    ]
