# Generated by Django 4.0.5 on 2022-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0009_remove_usuario2_usuario_remove_gpost_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpost',
            name='grupo',
            field=models.CharField(default='Random', max_length=255),
        ),
    ]
