# Generated by Django 4.0.5 on 2022-07-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0012_alter_grupo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpost',
            old_name='grupoG',
            new_name='grupo',
        ),
    ]
