# Generated by Django 4.0.5 on 2022-09-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0020_gcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcomments',
            name='grupoID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion2.grupo'),
        ),
    ]
