# Generated by Django 4.0.5 on 2022-06-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_post_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CuerpoPost',
            field=models.CharField(max_length=1000),
        ),
    ]
