# Generated by Django 4.0.5 on 2022-06-28 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_alter_post_cuerpopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CuerpoPost',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
