# Generated by Django 4.0.5 on 2022-07-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0009_alter_post_autor'),
        ('Aplicacion1', '0012_alter_post_imagen'),
    ]

    operations = [
    ]
