# Generated by Django 4.0.5 on 2022-07-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0013_merge_0009_alter_post_autor_0012_alter_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
