# Generated by Django 4.0.5 on 2022-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0014_remove_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfilImagen',
            field=models.ImageField(default='default_perfil.jpg', upload_to=''),
        ),
    ]
