# Generated by Django 4.0.5 on 2022-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0019_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Subir video'),
        ),
    ]
